import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
test.setTimeout(240000);
  await page.goto('https://depileve.com/es/coleccion/ceras-es/cera-film/');
  await page.getByRole('main').getByRole('link', { name: 'Ceras' }).click();
  await page.getByRole('link', { name: 'Visitar la categoría de producto Cera en tiras' }).click();
  await page.getByRole('link', { name: 'Visitar la categoría de producto Latas de cera sin bandas' }).click();
  await page.locator('#ajax-content-wrap').getByRole('link', { name: 'Cera en tiras' }).click();
  await page.getByRole('link', { name: 'Visitar la categoría de producto Roll and Go' }).click();
  await page.getByRole('link', { name: 'Cera en tiras' }).nth(1).click();
  await page.getByRole('link', { name: 'Visitar la categoría de producto Roll and Go' }).click();
  await page.getByLabel('Roll & go pink', { exact: true }).click();
  await page.getByRole('link', { name: 'Cera en tiras' }).nth(1).click();
  await page.getByRole('link', { name: 'Visitar la categoría de producto Roll-on' }).click();
  await page.getByLabel('Bush tea wax', { exact: true }).click();
  await page.getByRole('link', { name: 'Ceras' }).nth(1).click();
  await page.getByRole('link', { name: 'Visitar la categoría de producto Cera Film' }).click();
  await page.getByLabel('Brasilia', { exact: true }).click();
  await page.getByRole('link', { name: 'Cera Film' }).nth(1).click();
  await page.getByRole('main').getByRole('link', { name: 'Ceras' }).click();
  await page.getByRole('link', { name: 'Visitar la categoría de producto Cera tradicional' }).click();
  await page.getByRole('link', { name: 'Visitar la categoría de producto Bees Wax' }).click();
  await page.getByLabel('Azulene bio beads', { exact: true }).click();
  await page.getByRole('link', { name: 'Cera tradicional' }).nth(1).click();
  await page.getByRole('link', { name: 'Visitar la categoría de producto Bio Wax' }).click();
  await page.getByLabel('Chlorophyl bio tray', { exact: true }).click();
  await page.getByRole('link', { name: 'Ceras' }).nth(1).click();
  await page.getByRole('link', { name: 'Inicio' }).click();
});